# Generated by Django 3.0.8 on 2020-09-14 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetic', '0002_auto_20200914_1815'),
        ('store', '0007_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aesthetic.Collection'),
        ),
    ]
