# Generated by Django 3.0.8 on 2020-09-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionImages',
            new_name='CollectionImage',
        ),
    ]
